name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    name: ${{ matrix.os }}-stack-${{ matrix.stackage }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        stackage: ['nightly', 'lts-22']
    steps:
      - uses: actions/checkout@v4
      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-no-global: true
      - uses: actions/cache@v3
        with:
          path: ~/.stack
          key: stack-${{ matrix.os }}-${{ matrix.stackage }}-${{ hashFiles('stack.yaml') }}
      - name: Build
        run: |
          stack build
      - name: Test
        run: |
          stack test
